version: "3.8"
services:
  # Postgres
  postgres:
    restart: always
    image: postgres:13
    container_name: database
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mllgrm_db
    ports:
      - "5431:5432"
    healthcheck:
      test: [ "CMD", "pg_isready","-q","-d", "mllgrm_db", "-U","postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - milligram-net
  # Redis
  redis:
    restart: always
    image: redis:5
    container_name: cache
    volumes:
      - redis-data:/var/lib/redis
    ports:
      - "6378:6379"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - milligram-net
  #RabbitMQ
  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    container_name: queue
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/data/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - milligram-net
  # Flask|Keras Models Server
  deep:
    restart: always
    container_name: deep
    build:
      context: ./deep/
      dockerfile: ./deploy/Dockerfile
    env_file:
      - ./deep/.env
    ports:
      - "18001:18000"
    healthcheck:
      test: [ "CMD","curl", "-f", "http://localhost:18000/api/v3/health" ]
      interval: 20s
      timeout: 5s
      retries: 10
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - deep-data:/app/deep/data
    networks:
      - milligram-net
  # FastAPI|Socketio Server
  bridge:
    restart: always
    container_name: bridge
    build:
      context: ./bridge/
      dockerfile: ./deploy/Dockerfile
    env_file:
      - ./bridge/.env
    ports:
      - "18100:18100"
    healthcheck:
      test: [ "CMD","curl", "-f", "http://localhost:18100/api/v3/health" ]
      interval: 20s
      timeout: 5s
      retries: 10
    depends_on:
      redis:
        condition: service_healthy
      deep:
        condition: service_healthy
    networks:
      - milligram-net
  # Django Server
  server:
    restart: always
    container_name: server
    build:
      context: ./server/
      dockerfile: ./deploy/docker/server.Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "18200:18200"
    healthcheck:
      test: [ "CMD","curl", "-f", "http://localhost:18200/api/v3/health/" ]
      interval: 20s
      timeout: 5s
      retries: 10
    depends_on:
      postgres:
        condition: service_healthy
      bridge:
        condition: service_healthy
    volumes:
      - static-data:/app/server/static
      - media-data:/app/server/media
    networks:
      - milligram-net
  # Celery Worker & Beat
  celery:
    restart: always
    container_name: scheduler
    build:
      context: ./server/
      dockerfile: ./deploy/docker/celery.Dockerfile
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/data/
    depends_on:
      server:
        condition: service_healthy
    networks:
      - milligram-net
  # AioGram Bot
#  bot:
#    restart: always
#    container_name: milligram-bot
#    build:
#      context: ./bot/
#      dockerfile: ./deploy/Dockerfile
#    ports:
#      - "13504:13504"
#    depends_on:
#      server:
#        condition: service_healthy
#    networks:
#      - milligram-net
networks:
  milligram-net:
    driver: bridge
volumes:
  postgres-data: { }
  redis-data: { }
  rabbitmq-data: { }
  static-data: { }
  media-data: { }
  deep-data: { }
  ftp-data: { }